apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: server-policy
spec:
  ingress:
    - fromEntities:
        - cluster       
  egress:
    - toEntities:
        - cluster       
  endpointSelector: {}  
